c_compiler:                # [linux]
  - gcc                    # [linux]
c_compiler_version:        # [linux]
  - 11                     # [linux]
cxx_compiler:              # [linux]
  - gxx                    # [linux]
cxx_compiler_version:      # [linux]
  - 11                     # [linux]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
libevent:
  - "2.1.10"
  - "2.1.12"
